package dev.sharpwave.quadmage.gui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFbd0041)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryVariant = Color(0xFFffdade)
val md_theme_light_onPrimaryContainer = Color(0xFF40000f)
val md_theme_light_secondary = Color(0xFF765659)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryVariant = Color(0xFFffdadc)
val md_theme_light_onSecondaryContainer = Color(0xFF2c1518)
val md_theme_light_tertiary = Color(0xFF785930)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffddb3)
val md_theme_light_onTertiaryContainer = Color(0xFF2a1700)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a1a)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a1a)
val md_theme_light_surfaceVariant = Color(0xFFf4ddde)
val md_theme_light_onSurfaceVariant = Color(0xFF524344)
val md_theme_light_outline = Color(0xFF847374)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeee)
val md_theme_light_inverseSurface = Color(0xFF362f2f)

val md_theme_dark_primary = Color(0xFFffb2bb)
val md_theme_dark_onPrimary = Color(0xFF67001e)
val md_theme_dark_primaryVariant = Color(0xFF91002e)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdade)
val md_theme_dark_secondary = Color(0xFFe6bdc0)
val md_theme_dark_onSecondary = Color(0xFF44292c)
val md_theme_dark_secondaryVariant = Color(0xFF5d3f42)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdadc)
val md_theme_dark_tertiary = Color(0xFFe8bf8e)
val md_theme_dark_onTertiary = Color(0xFF442b06)
val md_theme_dark_tertiaryContainer = Color(0xFF5d411b)
val md_theme_dark_onTertiaryContainer = Color(0xFFffddb3)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a1a)
val md_theme_dark_onBackground = Color(0xFFece0e0)
val md_theme_dark_surface = Color(0xFF201a1a)
val md_theme_dark_onSurface = Color(0xFFece0e0)
val md_theme_dark_surfaceVariant = Color(0xFF524344)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c1c2)
val md_theme_dark_outline = Color(0xFF9f8c8d)
val md_theme_dark_inverseOnSurface = Color(0xFF201a1a)
val md_theme_dark_inverseSurface = Color(0xFFece0e0)

val seed = Color(0xFFbd0041)
val error = Color(0xFFba1b1b)